### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by JacobLinCool** [JacobLinCool/gradio-rs#3]
I think it's possible, but I may need to figure out the right feature flags for Tokio and Reqwest.

Some references:

- https://docs.rs/tokio/latest/tokio/#wasm-support
- https://docs.rs/reqwest/latest/reqwest/#wasm

**Comment by JacobLinCool** [comment]
It doesn't seem that easy to support WASM.

It's simple to find out the flag set. The following seems to be working:
```toml

[features]
default = ["tokio/rt-multi-thread"]
wasm = ["getrandom/js", "tokio/time", "tokio/io-util"]

[dependencies]
# others
getrandom = { version = "0.2.15", optional = true }
tokio = { version = "1.38.1", features = ["macros", "rt"] }
```

Then there are 2 problems to resolve. The first is that reqwest does not support cookies in WASM. (There are some PRs for that: https://github.com/seanmonstar/reqwest/pull/2360, https://github.com/seanmonstar/reqwest/pull/1753, and https://github.com/seanmonstar/reqwest/pull/1449.) The second is that we need to provide a new method to upload files from memory since WASM does not have a filesystem.
